"""add inventory movement ledger

Revision ID: 8487fdd19724
Revises: d8f168842895
Create Date: 2026-08-08 00:08:53.484204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8487fdd19724'
down_revision: Union[str, None] = 'd8f168842895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('balance_before', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance_after >= 0', name='ck_inventory_movements_balance_after_non_negative'),
    sa.CheckConstraint('balance_before >= 0', name='ck_inventory_movements_balance_before_non_negative'),
    sa.CheckConstraint('quantity <> 0', name='ck_inventory_movements_quantity_non_zero'),
    sa.ForeignKeyConstraint(['batch_id'], ['product_batches.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['warehouse_locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_movements_batch_id', 'inventory_movements', ['batch_id'], unique=False)
    op.create_index('ix_inventory_movements_created_at', 'inventory_movements', ['created_at'], unique=False)
    op.create_index('ix_inventory_movements_location_id', 'inventory_movements', ['location_id'], unique=False)
    op.create_index('ix_inventory_movements_movement_type', 'inventory_movements', ['movement_type'], unique=False)
    op.create_index('ix_inventory_movements_product_id', 'inventory_movements', ['product_id'], unique=False)
    op.create_index('ix_inventory_movements_reference', 'inventory_movements', ['reference_type', 'reference_id'], unique=False)
    op.create_index('ix_inventory_movements_warehouse_id', 'inventory_movements', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventory_movements_warehouse_id', table_name='inventory_movements')
    op.drop_index('ix_inventory_movements_reference', table_name='inventory_movements')
    op.drop_index('ix_inventory_movements_product_id', table_name='inventory_movements')
    op.drop_index('ix_inventory_movements_movement_type', table_name='inventory_movements')
    op.drop_index('ix_inventory_movements_location_id', table_name='inventory_movements')
    op.drop_index('ix_inventory_movements_created_at', table_name='inventory_movements')
    op.drop_index('ix_inventory_movements_batch_id', table_name='inventory_movements')
    op.drop_table('inventory_movements')
    # ### end Alembic commands ###
