"""initial

Revision ID: 8e8cbc77fd7b
Revises: 
Create Date: 2026-06-13 22:39:34.054346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e8cbc77fd7b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('products', 'product_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('products', 'product_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
