"""add purchase order received quantity

Revision ID: 935925e73f2d
Revises: 8487fdd19724
Create Date: 2026-08-08 14:57:26.082551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '935925e73f2d'
down_revision: Union[str, None] = '8487fdd19724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_items', sa.Column('received_quantity', sa.Numeric(precision=18, scale=3), server_default='0', nullable=False))
    op.alter_column('purchase_order_items', 'po_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('purchase_order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('purchase_order_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_order_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('purchase_order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('purchase_order_items', 'po_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('purchase_order_items', 'received_quantity')
    # ### end Alembic commands ###
