"""add stock balances

Revision ID: bc773a4eb44e
Revises: 68a643aabb5e
Create Date: 2026-08-07 14:56:13.294275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc773a4eb44e'
down_revision: Union[str, None] = '68a643aabb5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column(
        "on_hand_qty",
        sa.Numeric(precision=18, scale=3),
        server_default=sa.text("0"),
        nullable=False,
    ),
    sa.Column(
        "reserved_qty",
        sa.Numeric(precision=18, scale=3),
        server_default=sa.text("0"),
        nullable=False,
    ),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('on_hand_qty >= 0', name='ck_stock_balances_on_hand_non_negative'),
    sa.CheckConstraint('reserved_qty <= on_hand_qty', name='ck_stock_balances_reserved_lte_on_hand'),
    sa.CheckConstraint('reserved_qty >= 0', name='ck_stock_balances_reserved_non_negative'),
    sa.ForeignKeyConstraint(
        ["batch_id"],
        ["product_batches.id"],
        name="fk_stock_balances_batch_id",
    ),
    sa.ForeignKeyConstraint(
        ["location_id"],
        ["warehouse_locations.id"],
        name="fk_stock_balances_location_id",
    ),
    sa.ForeignKeyConstraint(
        ["product_id"],
        ["products.id"],
        name="fk_stock_balances_product_id",
    ),
        sa.ForeignKeyConstraint(
        ["warehouse_id"],
        ["warehouses.id"],
        name="fk_stock_balances_warehouse_id",
    ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_balances_batch_id', 'stock_balances', ['batch_id'], unique=False)
    op.create_index('ix_stock_balances_location_id', 'stock_balances', ['location_id'], unique=False)
    op.create_index('ix_stock_balances_product_id', 'stock_balances', ['product_id'], unique=False)
    op.create_index('ix_stock_balances_warehouse_id', 'stock_balances', ['warehouse_id'], unique=False)
    op.create_index('uq_stock_balances_no_batch', 'stock_balances', ['product_id', 'warehouse_id', 'location_id'], unique=True, postgresql_where=sa.text('batch_id IS NULL'))
    op.create_index('uq_stock_balances_with_batch', 'stock_balances', ['product_id', 'warehouse_id', 'location_id', 'batch_id'], unique=True, postgresql_where=sa.text('batch_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_stock_balances_with_batch', table_name='stock_balances', postgresql_where=sa.text('batch_id IS NOT NULL'))
    op.drop_index('uq_stock_balances_no_batch', table_name='stock_balances', postgresql_where=sa.text('batch_id IS NULL'))
    op.drop_index('ix_stock_balances_warehouse_id', table_name='stock_balances')
    op.drop_index('ix_stock_balances_product_id', table_name='stock_balances')
    op.drop_index('ix_stock_balances_location_id', table_name='stock_balances')
    op.drop_index('ix_stock_balances_batch_id', table_name='stock_balances')
    op.drop_table('stock_balances')
    # ### end Alembic commands ###
