server {
    listen 80;
    server_name localhost;

    server_tokens off;

    client_max_body_size 20M;

    # Security Headers
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;

    # Compression
    gzip on;
    gzip_vary on;
    gzip_comp_level 5;
    gzip_min_length 1024;

    gzip_types
        application/json
        application/javascript
        application/xml
        text/css
        text/plain;

    location / {
        proxy_pass http://api:8081;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 10s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}