"use client";

import * as React from "react";
import Link from "next/link";
import { Download, FileSpreadsheet, Loader2 } from "lucide-react";

import { PageHeader } from "@/components/ui/page-header";
import { Button } from "@/components/ui/button";
import { REPORTS, REPORT_GROUPS } from "@/lib/reports/registry";
import { REPORT_EXPORTS, type ReportExport } from "@/lib/api/schemas/reports";
import { useReportExport } from "@/lib/query/reports";

function ReportCard({ slug, title, blurb, Icon }: { slug: string; title: string; blurb: string; Icon: React.ElementType }) {
  return (
    <Link
      href={`/reports/${slug}`}
      className="group flex flex-col gap-2 rounded-[var(--r-md)] border border-[var(--border)] bg-[var(--surface)] p-4 transition-colors hover:border-[var(--accent)] hover:bg-[var(--accent-subtle)] focus-visible:outline-2 focus-visible:outline-[var(--focus)]"
    >
      <span className="flex items-center gap-2">
        <Icon aria-hidden className="h-4 w-4 text-[var(--muted)] group-hover:text-[var(--accent)]" />
        <span className="text-[13.5px] font-semibold">{title}</span>
      </span>
      <span className="text-[12px] leading-[1.45] text-[var(--faint)]">{blurb}</span>
    </Link>
  );
}

function ExportCard({ ex }: { ex: ReportExport }) {
  const { running, run } = useReportExport();
  const [params, setParams] = React.useState<Record<string, string>>(
    Object.fromEntries((ex.params ?? []).map((p) => [p.name, p.default])),
  );
  return (
    <div className="flex flex-col gap-2 rounded-[var(--r-md)] border border-[var(--border)] bg-[var(--surface)] p-4">
      <span className="flex items-center gap-2">
        <FileSpreadsheet aria-hidden className="h-4 w-4 text-[var(--muted)]" />
        <span className="text-[13.5px] font-semibold">{ex.title}</span>
      </span>
      <span className="text-[12px] leading-[1.45] text-[var(--faint)]">{ex.description}</span>
      {ex.params?.length ? (
        <div className="mt-1 flex flex-wrap gap-2">
          {ex.params.map((p) => (
            <label key={p.name} className="flex items-center gap-1 text-[11px] text-[var(--muted)]">
              {p.label}
              <input
                inputMode={p.kind === "int" ? "numeric" : "decimal"}
                aria-label={`${ex.title} — ${p.label}`}
                className="h-8 w-20 rounded-[var(--r-sm)] border border-[var(--border-strong)] bg-[var(--surface)] px-2 text-[12px] tabular-nums outline-none focus-visible:outline-2 focus-visible:outline-[var(--focus)]"
                value={params[p.name] ?? ""}
                onChange={(e) => {
                  const v = e.currentTarget.value;
                  setParams((s) => ({ ...s, [p.name]: v }));
                }}
              />
            </label>
          ))}
        </div>
      ) : null}
      <Button
        variant="secondary"
        className="mt-1 self-start"
        disabled={running}
        onClick={() => run(ex.path, ex.params?.length ? params : undefined)}
      >
        {running ? <Loader2 aria-hidden className="h-4 w-4 animate-spin" /> : <Download aria-hidden className="h-4 w-4" />}
        {running ? "Preparing…" : "Download .xlsx"}
      </Button>
    </div>
  );
}

export function ReportsLanding() {
  return (
    <div className="flex flex-col gap-6">
      <PageHeader
        title="Reports"
        subtitle="Read-only operational reports and spreadsheet exports. Every value is generated by the backend."
      />

      {REPORT_GROUPS.map((group) => (
        <section key={group} className="flex flex-col gap-2">
          <h2 className="wc-section-label">{group}</h2>
          <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-3">
            {REPORTS.filter((r) => r.group === group).map((r) => (
              <ReportCard key={r.slug} slug={r.slug} title={r.title} blurb={r.blurb} Icon={r.icon} />
            ))}
          </div>
        </section>
      ))}

      <section className="flex flex-col gap-2">
        <h2 className="wc-section-label">Exports</h2>
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4">
          {REPORT_EXPORTS.map((ex) => (
            <ExportCard key={ex.key} ex={ex} />
          ))}
        </div>
      </section>
    </div>
  );
}
